### ISSUE TITLE
fidget breaks nim CI again

### ISSUE THREAD

**Issue by timotheecour** [treeform/fidget#133]
(previous instances: https://github.com/treeform/fidget/issues/121 + other more recent IIRC)

as mentioned in https://github.com/treeform/fidget/issues/121#issuecomment-742918145, it would be good to find and fix root cause for such regressions; 

EDIT: looks like it's https://github.com/guzba/nimsimd/commit/538c47f1029cf14a40ad0f2f4f0ef0bf8bcab2e3#r46409625

## logs
  FAIL: fidget c
https://github.com/nim-lang/Nim/pull/16831/checks?check_run_id=1775941555

   Compiling /Users/runner/work/Nim/Nim/pkgstemp/fidget/tests/test (from package fidget) using c backend
  /Users/runner/.nimble/pkgs/pixie-0.0.16/pixie/images.nim(182, 30) Error: type mismatch: got <int literal(255)>
  but expected one of: 
  func mm_set1_epi8(a: int8): M128i
    first type mismatch at position: 1
    required type for a: int8
    but expression '255' is of type: int literal(255)
  
  expression: mm_set1_epi8(255)
         Tip: 73 messages have been suppressed, use --verbose to show them.
       Error: Execution failed with exit code 256
          ... Command: /Users/runner/work/Nim/Nim/bin/nim c --noNimblePath -d:NimblePkgVersion=0.7.1 --path:/Users/runner/.nimble/pkgs/chroma-0.2.1 --path:/Users/runner/.nimble/pkgs/typography-0.7.4 --path:/Users/runner/.nimble/pkgs/pixie-0.0.16 --path:/Users/runner/.nimble/pkgs/vmath-0.4.1 --path:/Users/runner/.nimble/pkgs/chroma-0.2.1 --path:/Users/runner/.nimble/pkgs/zippy-0.5.2 --path:/Users/runner/.nimble/pkgs/flatty-0.1.5 --path:/Users/runner/.nimble/pkgs/nimsimd-1.0.0 --path:/Users/runner/.nimble/pkgs/bumpy-1.0.1 --path:/Users/runner/.nimble/pkgs/vmath-0.4.1 --path:/Users/runner/.nimble/pkgs/vmath-0.4.1 --path:/Users/runner/.nimble/pkgs/chroma-0.2.1 --path:/Users/runner/.nimble/pkgs/print-0.2.0 --path:/Users/runner/.nimble/pkgs/bumpy-1.0.1 --path:/Users/runner/.nimble/pkgs/vmath-0.4.1 --path:/Users/runner/.nimble/pkgs/flatty-0.1.5 --path:/Users/runner/.nimble/pkgs/pixie-0.0.16 --path:/Users/runner/.nimble/pkgs/vmath-0.4.1 --path:/Users/runner/.nimble/pkgs/chroma-0.2.1 --path:/Users/runner/.nimble/pkgs/zippy-0.5.2 --path:/Users/runner/.nimble/pkgs/flatty-0.1.5 --path:/Users/runner/.nimble/pkgs/nimsimd-1.0.0 --path:/Users/runner/.nimble/pkgs/bumpy-1.0.1 --path:/Users/runner/.nimble/pkgs/vmath-0.4.1 --path:/Users/runner/.nimble/pkgs/vmath-0.4.1 --path:/Users/runner/.nimble/pkgs/print-0.2.0 --path:/Users/runner/.nimble/pkgs/opengl-1.2.6 --path:/Users/runner/.nimble/pkgs/x11-1.1 --path:/Users/runner/.nimble/pkgs/html5_canvas-1.3 --path:/Users/runner/.nimble/pkgs/staticglfw-4.1.2 --path:/Users/runner/.nimble/pkgs/opengl-1.2.6 --path:/Users/runner/.nimble/pkgs/x11-1.1 --path:/Users/runner/.nimble/pkgs/cligen-1.4.0 --path:/Users/runner/.nimble/pkgs/supersnappy-2.0.0 --path:/Users/runner/.nimble/pkgs/bumpy-1.0.1 --path:/Users/runner/.nimble/pkgs/vmath-0.4.1 --hints:off -r --path:. /Users/runner/work/Nim/Nim/pkgstemp/fidget/tests/test

**Comment by guzba** [comment]
This is resolved, reran on my fork, is green. https://github.com/guzba/fidget/runs/1779879598

**Comment by timotheecour** [comment]
@guzba can you make a PR to revert https://github.com/nim-lang/Nim/pull/16842?

**Comment by narimiran** [comment]
> This is resolved

Doesn't seem like it is — it still fails on Nim 1.4.x CIs, for example: https://github.com/nim-lang/Nim/runs/1856156288#step:11:602

**Comment by treeform** [comment]
I really like including fidget as an important nim repo that Nim compiler tests against. It makes me proud of the work we have done.

Yet, we are working a ton on Fidget/Pixie/Typography. Maybe its best to keep it out of the CI for now, until we are more done with the project?

Feel free to reopen if you disagree.

**Comment by timotheecour** [comment]
> Maybe its best to keep it out of the CI for now, until we are more done with the project?

how about:
* reopen this issue
* make sure important_packages keeps testing fidget, but at latest release tag, not HEAD:
```nim
# pkg1 "fidget" # pending https://github.com/treeform/fidget/issues/133
```
=>
```nim
pkg1 "fidget", useHead = false
```
* then fidget can keep being developped, and CI won't break latest release tag

furthermore, we can also add support for this in imporant_packages:

`pkg1 "fidget", hash = 0.1.3` # or any other hash starting with a `#`
in case some packages (eg fidget) needs to have unstable release tags (eg odd numbers)

**Comment by narimiran** [comment]
> `pkg1 "fidget", useHead = false`

I'm now adding this, together with adding `pixie`.

> furthermore, we can also add support for this in imporant_packages:
> `pkg1 "fidget", hash = 0.1.3` # or any other hash starting with a #

Pass.

**Comment by timotheecour** [comment]
@treeform 
see logs for https://github.com/nim-lang/Nim/pull/17229 with `useHead=false`:
```
       Error: Cannot satisfy the dependency on chroma 0.2.4 and chroma 0.2.3
```
